/*----------------------------------------------------------------------------

  WhiteBoardCorrection

  This code is part of the following publication and was subject
  to peer review:

    "WhiteBoardCorrection" by Nekomeshi

  Copyright (c) Nekomeshi <Nekomeshi312@gmail.com>

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program. If not, see <http://www.gnu.org/licenses/>.

  ----------------------------------------------------------------------------*/


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nekomeshi312_whiteboardcorrection_DetectLines */

#ifndef _Included_com_nekomeshi312_whiteboardcorrection_DetectLines
#define _Included_com_nekomeshi312_whiteboardcorrection_DetectLines
#ifdef __cplusplus
extern "C" {
#endif
#undef com_nekomeshi312_whiteboardcorrection_DetectLines_MAX_LINE_NUM
#define com_nekomeshi312_whiteboardcorrection_DetectLines_MAX_LINE_NUM 500L
/*
 * Class:     com_nekomeshi312_whiteboardcorrection_DetectLines
 * Method:    detectLines
 * Signature: (JZJ[I)I
 */
JNIEXPORT jint JNICALL Java_com_nekomeshi312_whiteboardcorrection_DetectLines_detectLines
  (JNIEnv *, jobject, jlong, jboolean, jlong, jintArray);

/*
 * Class:     com_nekomeshi312_whiteboardcorrection_DetectLines
 * Method:    initLines
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_nekomeshi312_whiteboardcorrection_DetectLines_initLines
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_nekomeshi312_whiteboardcorrection_DetectLines
 * Method:    cleanupLines
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nekomeshi312_whiteboardcorrection_DetectLines_cleanupLines
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
